### ISSUE TITLE
Plugin only works on paper.

### ISSUE THREAD

**Issue by BlitzOffline** [heychazza/ChitChat#4]
The plugin only works on Paper. The readme mentions that it works on spigot as well which is false. Even tho paper has backwards compatible you are using features from paper that do not exist in spigot such as:
https://github.com/heychazza/ChitChat/blob/c86b87c95bf274dd5a96dc1d16ef7fd57fbbb973/src/main/java/sh/charlie/chitchat/listener/ChatListener.java#L29

and no I'm not going to PR a correction of the README lol.

**Comment by heychazza** [comment]
> The plugin only works on Paper. The readme mentions that it works on spigot as well which is false. Even tho paper has backwards compatible you are using features from paper that do not exist in spigot such as:
> 
> https://github.com/heychazza/ChitChat/blob/c86b87c95bf274dd5a96dc1d16ef7fd57fbbb973/src/main/java/sh/charlie/chitchat/listener/ChatListener.java#L29
> 
> and no I'm not going to PR a correction of the README lol.

Great spot, thank you!
